---
new_page_extension: md
auto_deploy: false
admin_path: ".vuepress/public/admin"
webhook_url: 
sections:
- type: document
  path: README.md
  label: Home
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: document
  path: resume.md
  label: Resume
- type: document
  path: about.md
  label: About
- type: document
  path: contact.md
  label: Contact
upload_dir: ".vuepress/public/media"
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
