---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: image
  type: file
  config:
    maxSize: 250
  label: image
- name: tags
  type: tag_list
  default: []
  label: tags
pages:
- projects/test2.md
- projects/super-projet.md
- projects/test.md
