---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  config:
    display_utc: false
    export_format: YYYY-MM-DD
- name: image
  type: file
  config:
    maxSize: 250
  label: image
- name: tags
  type: tag_list
  default: []
  label: tags
- name: excerpt
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: excerpt
- name: code
  type: text
  config:
    required: false
  label: code
- name: download
  type: text
  config:
    required: false
  label: download
pages:
- projects/san-francisco-ece-makers.md
- projects/jewelry-making.md
- projects/kasar-ai.md
- projects/fullcashprono-com.md
- projects/skateboard-press.md
- projects/growonline-fr-automated-indoor-growing.md
